### ISSUE TITLE
Running tests locally fails if host has less than 2 cuda devices

### ISSUE THREAD

**Issue by MaciejSkrabski** [WenjieDu/PyPOTS#123]
### Issue description

When developing locally the tests in `tests/test_tranining_on_multi_gpus.py` fail on a single-gpu host.

Possible fix: skip the tests in this module alltogether if host does not have 2 cuda-enabled devices minimum.

**Comment by WenjieDu** [comment]
I used `--ignore` to skip them, for example, in workflow [testing_daily#L55](https://github.com/WenjieDu/PyPOTS/blob/fe5a358b7a62f61f5134ad192257f247a90c38e4/.github/workflows/testing_daily.yml#L55). Your proposal is automatic and more reasonable. I have merged the PR. Thanks! 😉
