### ISSUE TITLE
How can I customize my own dataset to fit PyPOTS SOTA imputation models?

### ISSUE THREAD

**Issue by abhishekju06** [WenjieDu/PyPOTS#141]
### 1. Feature description

I want to run Pypots SOA models for my own dataset.

### 2. Motivation

I have a multivariate dataset and want to check how PyPots models are working on it for data imputation.

### 3. Your contribution

None so far

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by abhishekju06** [comment]
What does n_steps indicate in my dataset?
n_features represent the number of attributes, I suppose.
n_samples represent the len of dataframe, I suppose.

**Comment by WenjieDu** [comment]
`n_samples` indicate how many samples are in your dataset. `n_steps` is the number of time steps in each sample. You can use sliding window algo to generate such a 3D dataset from your original 2D dataset. 

Yes, of course, cleaning and normalization are included in preprocessing. You know, machine learning is not magic, you have to make things prepared for model processing.

**Comment by WenjieDu** [comment]
Please try simply search with google or github, I believe you can figure it out fast. This is not a complicate algorithm, just a simple method.

**Comment by abhishekju06** [comment]
Thanks a lo!

**Comment by WenjieDu** [comment]
My pleasure! @abhishekju06 Just remembered that you can find such a sliding window function from data-processing utilities [in SAITS repo here](https://github.com/WenjieDu/SAITS/blob/main/dataset_generating_scripts/data_processing_utils.py#L34-L46). If you using SAITS model for your data imputation and think it's helpful, please kindly consider to star 🌟 [SAITS repo](https://github.com/WenjieDu/SAITS/) to make more people notice this useful model. Many thanks!

**Comment by abhishekju06** [comment]
Should there be NaN present in my dataset before I generate the dataset?

**Comment by WenjieDu** [comment]
> Datasets are OK with missing values, of course, PyPOTS is designed for datasets with missing data. But after generation, indicating_mask and X_intact should not have NaNs, and the missing part in X_intact should be imputed with some values like 0. Because PyPOTS will use them for loss calculation. NaN in indicating_mask or X_intact will result in NaN loss, just like in your case.

Sorry for missing a `not` in my last reply, just fixed it: "after generation, indicating_mask and X_intact should not have NaNs".

**Comment by abhishekju06** [comment]
> According to the info you provided, I think the error is caused by the input data not properly prepared. Please check whether there are `NaN`s in `dataset_for_validating["indicating_mask"]` and `dataset_for_validating["X_intact"]`.

I have replaced NaN values with 0 in the 'indicating_mask'.
I guess, X_hat refers to X_intact. Thus, I have set it as the value for the key X_intact:

dataset_for_validating = {
    "X": group_val['X'][()],
    "X_intact": group_val['X_hat'][()],
    "indicating_mask": group_val['indicating_mask'][()],
}

**If not please let me know what X_intact stands for.**

In [SAITS](https://github.com/WenjieDu/SAITS/tree/main)/[dataset_generating_scripts](https://github.com/WenjieDu/SAITS/tree/main/dataset_generating_scripts)
/data_processing_utils.py 

in line 86  X_hat[indices_for_holdout] = np.nan  # X_hat contains artificial missing values 

It is evident that X_hat must contain NaN as it represents artificial missing values.

So where I am going wrong?

**Comment by abhishekju06** [comment]
Hi,
Please don't get me wrong. I have read the paper.
I just want to make clear what the **notations in the paper corresponds with the notation in the code**.
X cap
M cap
X tilde
I

Without your help it is not possible for me to understand.

**Comment by WenjieDu** [comment]
Please read it carefully and take a look at the model's implementation code [here](https://github.com/WenjieDu/SAITS/blob/main/modeling/saits.py#L32-L224) for reference.

**Comment by abhishekju06** [comment]
Thanks a ton!

**Comment by WenjieDu** [comment]
No problem. If you have further questions regarding the SAITS model, you're welcome to raise issues in SAITS repo https://github.com/WenjieDu/SAITS/issues.
