### ISSUE TITLE
Adding data having same TimeStamp but different source

### ISSUE THREAD

**Issue by abhishekju06** [WenjieDu/PyPOTS#146]
### Issue description

Hi Wenjie,

I want to prepare my dataset having same Timestamp but from different source. Can you please let me know how to do it?

**Comment by WenjieDu** [comment]
Please don't ask me too-general questions like this, much less it's not related to PyPOTS. I'm not a free tutor. If you want to raise a discussion, please at least show that you gave your thought to it. Google it and do your research first. Thanks.

**Comment by abhishekju06** [comment]
I didn't find any such preprocessing code that supports the generation of dataset having same timestamp but different sources in PyPOTS. That was the reason I asked you. Thanks for such reply.

**Comment by WenjieDu** [comment]
Out of question, a library couldn't and also is impossible to contain all functions that users may need, especially for such a personalized step as data preprocessing.

Some suggestions here. You can try to merge all features together, say you have 3 features for data from one source and you have 5 sources, then you have 15 features after merging. This is like the preprocessing of the dataset AirQuality in SAITS paper. Or you can organize different sources into one more dimension, say it location dim. Then you need models having the capability of handling the data with such one more dimension, like spatial-temporal models.

**Comment by abhishekju06** [comment]
Hi Wenjie,

Hope you are doing great.
Just wanted to know how to load and predict a model that I have trained
earlier.
The models are saved in folder ..\saits\20230718_T203937.
I cannot figure this out.
Please help

**Comment by abhishekju06** [comment]
Sorry to bother you.
I was able to figure it out with saits.load_model(model_path).

**Comment by WenjieDu** [comment]
No problem. You can follow me to receive the latest news about PyPOTS.
