### ISSUE TITLE
Log file output

### ISSUE THREAD

**Issue by NewKeyTo** [WenjieDu/PyPOTS#160]
### 1. Feature description

Allow training logs to be output to a file

### 2. Motivation

Adding the functionality to output logs to a file would be better

### 3. Your contribution

I will try to help

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hi Daozhan,

As we have discussed in private, you can make this happen with
```
from pypots.utils.logging import logger_creator
logger_creator.set_saving_path(".", "logs.pypots")
```

https://github.com/WenjieDu/PyPOTS/blob/4c08e051977a6591643c2f80a00694144d830f33/pypots/utils/logging.py#L109

But please note that `logger` in pypots.utils.logging is with the singleton pattern.
