### ISSUE TITLE
如果我有其他训练集，怎么利用你们的模型进行训练呢

### ISSUE THREAD

**Issue by xzscode** [WenjieDu/PyPOTS#168]
### Issue description

可以单单用你们的模型跑出结果吗，类似于outputs = model(X)的形式？

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
你好 Zhensi，当然可以，你可以参考tutorials https://github.com/WenjieDu/BrewPOTS中的输入格式
