### ISSUE TITLE
AttributeError in Import due to numpy version

### ISSUE THREAD

**Issue by eschlager** [WenjieDu/PyPOTS#174]
### 1. System Info

OS Windows 10
Python version 3.8
PyPOTS version 0.1.2

numpy 1.24.3

### 2. Information

- [X] The official example scripts
- [ ] My own created scripts

### 3. Reproduction

I just installed PyPOTS via conda. When running the PhysioNet2012 example, got an Error while importing: 

`
AttributeError: module 'numpy' has not attribute 'typeDict'
`

I had numpy version 1.24.3.
Downgrading to numpy 1.23.3 helped.

### 4. Expected behavior

The environment-dev.yml file says that numpy>=1.23.3 is required. However, numpy == 1.24.3 fails.
I did not check for other versions though.

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hi @eschlager, thank you very much for your information! I'm going to double-check it.

**Comment by WenjieDu** [comment]
Hi @eschlager, sorry for the delay. This is caused by dependency conflict, rather than by code in PyPOTS itself. As per the [NumPy 1.21.0 Release Notes](https://github.com/numpy/numpy/releases/tag/v1.21.0#:~:text=np.typeDict%20has%20been%20formally%20deprecated), `np.typeDict` has been formally deprecated. I think this error is raised by code in PyPOTS' other dependency libs. Could you please provide more details in the Traceback?

**Comment by eschlager** [comment]
Hey, 

this is the whole trace back when running the PyPOTS_Imputation tutorial:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 from pypots.data.generating import gene_physionet2012
      3 # Load the PhysioNet-2012 dataset
      4 physionet2012_dataset = gene_physionet2012(artificially_missing_rate=0.1)

File ~\AppData\Local\anaconda3\envs\env_sentinels\lib\site-packages\pypots\data\__init__.py:8
      1 """
      2 Expose all usable data manipulation classes and functions.
      3 """
      5 # Created by Wenjie Du <wenjay.du@gmail.com>
      6 # License: GPL-v3
----> 8 from .base import BaseDataset
      9 from .generating import (
     10     gene_complete_random_walk,
     11     gene_random_walk_for_classification,
     12     gene_incomplete_random_walk_dataset,
     13     gene_physionet2012,
     14 )
     15 from .load_specific_datasets import (
     16     list_supported_datasets,
     17     load_specific_dataset,
     18 )

File ~\AppData\Local\anaconda3\envs\env_sentinels\lib\site-packages\pypots\data\base.py:11
      8 from abc import abstractmethod
      9 from typing import Union, Optional, Tuple, Iterable
---> 11 import h5py
     12 import numpy as np
     13 import torch

File ~\AppData\Local\anaconda3\envs\env_sentinels\lib\site-packages\h5py\__init__.py:46
     37     _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
     38            "this may cause problems").format(
     39             '{0}.{1}.{2}'.format(*version.hdf5_version_tuple),
     40             '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
     41     ))
     44 _errors.silence_errors()
---> 46 from ._conv import register_converters as _register_converters
     47 _register_converters()
     49 from .h5z import _register_lzf

File h5py\_conv.pyx:1, in init h5py._conv()

File h5py\h5t.pyx:293, in init h5py.h5t()

File ~\AppData\Local\anaconda3\envs\env_sentinels\lib\site-packages\numpy\__init__.py:320, in __getattr__(attr)
    317     from .testing import Tester
    318     return Tester
--> 320 raise AttributeError("module {!r} has no attribute "
    321                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'typeDict'
```

**Comment by WenjieDu** [comment]
Yeah, like I said, this error is not caused by logic code in PyPOTS, but by the dependency lib h5py. Installing a proper version of h5py (maybe you should bump it up) or downgrading your numpy to satisfy your h5py can solve this problem.

**Comment by eschlager** [comment]
Yes, I just wanted to point out that environment-dev.yml file says that numpy>=1.23.3 is required; which is not enough requirement apparently.

**Comment by WenjieDu** [comment]
Thanks for your information.
