### ISSUE TITLE
Visualize self-attention matrix

### ISSUE THREAD

**Issue by gugababa** [WenjieDu/PyPOTS#178]
### 1. Feature description

Hi! Would it be possible to add an option to visualize the final (and intermediate) self-attention maps/matrices for the SAITS model? Thank you!

### 2. Motivation

My work is currently using the SAITS model to impute a spectrum to reduce the acquisition time of an MRI scan. I would like to find the optimal acquisition protocol by determining the attention of each point, as points that have a higher attention score are more likely to be included in the acquisition protocol. 

### 3. Your contribution

I can contribute to the code base and try to add this feature myself, although this may take some time as I will have to parse through the repo.

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hey @gugababa, thanks for starting this issue! Your request is similar to the one @vemuribv asked for in #177. You both want something from the representation learned by models, not the final results, but could be useful to analyze models' behavior. Sounds reasonable and necessary. So let's make it!

Could you please make a PR to add a function that helps visualize the SAITS model's attention matrix? I will adjust the framework API to let the model return its attention matrix for your function to do the visualization task. What do you think?

**Comment by gugababa** [comment]
Hi Wenjie,

That sounds good to me! If I have any questions about the current API, I
will let you know. I'll create the function soon.

Best,
Anshu

**Comment by WenjieDu** [comment]
Cool! Let me know if you have any questions, Anshu ;-)

Best Regards,
Wenjie

**Comment by gugababa** [comment]
Hi Wenjie,

I was just wondering what the shape of the attention weights are so I can
apply the correct assertions. I assume that each layer within the
multi-attention head will return their own attention weights, and the
attention weights across the heads of a layer are averaged based on what I
see in the API. Are the attention weights given for each batch as well? In
addition, I am writing the function to be compatible with Tensorboard's
image summary function so it can be written to the final Tensorboard file.

Let me know as soon as you can, no rush. :) Thanks again!

Best,
Anshu

**Comment by WenjieDu** [comment]
Hi Anshu, 

Self-attention calculates the similarities between time steps, and the attention weight map represents the similarities. For each attention layer, the shape of the attention weights is `[batch_size, n_heads, n_steps, n_steps]`. So that depends on whether you want to visualize all layers' attention weights or only the last layer's. Regarding the weighted-combination block in SAITS, yes, the weights are averaged across the heads, so its shape is `[batch_size, n_steps, n_steps]`, and they're taken from the last layer of the 2nd DMSA block.
