### ISSUE TITLE
Adding TimesNet as an imputation model

### ISSUE THREAD

**Issue by WenjieDu** [WenjieDu/PyPOTS#250]
### 1. Model description

[TimesNet: Temporal 2D-Variation Modeling for General Time Series Analysis](https://arxiv.org/abs/2210.02186) from ICLR 2023.

This model can be applied to multiple tasks in time series analysis, e.g. imputation, classification, forecasting, and anomaly detection, but it is not a multi-task model, namely, it cannot be end-to-end trained on multiple tasks simultaneously. Additionally, except for the imputation task, TimesNet doesn't work on POTS data, i.e. for classification, forecasting, and anomaly detection tasks, it needs complete time-series samples as input.

However, we can add it to PyPOTS as an imputation model.

### 2. Check open-source status

- [X] The model implementation is publicly available

### 3. Provide useful information for the implementation

https://github.com/thuml/Time-Series-Library/blob/main/models/TimesNet.py

**Comment by 591343** [comment]
When can I use TimesNet in release ?

**Comment by WenjieDu** [comment]
Hi @591343, if you like PyPOTS, please star🌟 this repo to make more people notice this useful toolkit. To receive the latest news about PyPOTS, you can follow me on GitHub.

Regarding your question, you can use it right now. The sub-branch integrating TimesNet has been merged into the main branch.
