### ISSUE TITLE
Possible to implement CSDI as a forecasting model for POTS data

### ISSUE THREAD

**Issue by WenjieDu** [WenjieDu/PyPOTS#264]
### 1. Feature description

Although, in the CSDI paper, the authors discussed using the model for time series forecasting, their experiments and scenarios are for complete time series. However, the model is possible for POTS forecasting.

### 2. Motivation

Make CSDI a forecasting model in PyPOTS.

### 3. Your contribution

I'm currently overloaded. If anyone is interested in this task, please discuss it below to see if you can take it.

The CSDI model has been included in PyPOTS as an imputation model, so necessary modules are all available already.

**Comment by ahmaddroobi99** [comment]
I start working on it, to get familiar with code and understand its infrastructure.

**Comment by WenjieDu** [comment]
Many thanks, Ahmad. I've assigned this to you and me. I can help you at any time, please just start the discussion here if you need any information or assistance. And once you make the PR, I'll review the code.

**Comment by ahmaddroobi99** [comment]
Is this the Algorithm that should be implemented, could you describe more, As I understand now it will be in forecasting algorithms in PyPOTS. 

<img width="416" alt="image" src="https://github.com/WenjieDu/PyPOTS/assets/55400034/f0671717-243e-4fab-b844-059254080bb5">

**Comment by WenjieDu** [comment]
@ahmaddroobi99 The graph you posted is an overview of how CSDI works: input, process, and output.

Here are some clues and suggestions from me:

1. read the paper and figure out the model itself first. I believe you've done well with this;
2. walk through the code under this path https://github.com/WenjieDu/PyPOTS/blob/main/pypots/imputation/csdi and figure out how CSDI is implemented as an imputation model here. The CSDI code in PyPOTS keeps the same logic as the official implementation https://github.com/ermongroup/CSDI but is in a more unified PyPOTS way;
3. read the code in https://github.com/ermongroup/CSDI/blob/main/exe_forecasting.py and the code it imports. This script will help you learn how CSDI works on the forecasting task;
4. get your hands on turning the imputation CSDI in PyPOTS into a forecasting model. Basically, you need to do some refactoring work to adapt the code for the forecasting task;

Let me know if you have any further questions.

**Comment by LINGLONGQIAN** [comment]
Hi @WenjieDu and @ahmaddroobi99 maybe I can help on this as well, I have some experience in CSDI code and had also familiar with their code and paper.

**Comment by WenjieDu** [comment]
Thanks, @LINGLONGQIAN, good to know you'd like to help. I'm going to check with Ahmad to see how things are going on his side. Then we can determine which part you can take care of.

**Comment by WenjieDu** [comment]
Ahmad @ahmaddroobi99 recently has been very busy with his own work. After communication, Linglong @LINGLONGQIAN and I will take care of this issue.
