### ISSUE TITLE
New Model

### ISSUE THREAD

**Issue by firmai** [WenjieDu/PyPOTS#295]
### 1. Model description

It would be interesting to add the leader in this benchmark to the imputation pipeline. Btw, nice library :)

https://github.com/thuml/Time-Series-Library/tree/main

### 2. Check open-source status

- [X] The model implementation is publicly available

**Comment by WenjieDu** [comment]
Thanks, Derek. Will do. 😎

**Comment by WenjieDu** [comment]
The above PRs tried to add corresponding imputation models into PyPOTS. They take the official code repositories from the paper authors and the implementations from THUML/Time-Series-Library as references. However, I note that different from the SAITS training strategy, the model implementations in THUML/Time-Series-Library do not take the missing mask as a part of the input, while this could make the models confused by observed zeros and missing values filled by zeros. This may degrade the models' imputation performance. 

Now that the SAITS training strategy has been validated and now widely adopted in imputation models, we should also apply it to improve the imputation accuracy of the above models.

**Comment by WenjieDu** [comment]
I'm closing this issue. More time-series related models will be adapted into PyPOTS. The SAITS embedding strategy will still be applied to these models for enabling them to work on POTS data.
