### ISSUE TITLE
Raindrop implementation questions

### ISSUE THREAD

**Issue by lucasmiranda42** [WenjieDu/PyPOTS#299]
### Issue description

Hi all, and thanks for such a great package!

I'm currently working on the raindrop architecture, and I have a couple of questions regarding your implementation of the message passing algorithm included [here](https://github.com/mims-harvard/Raindrop/blob/main/code/Ob_propagation.py):

1. The first is where is the message_selfattention method (implementing as far as I can read the attention mechanism described in the paper) used in the code. I tried inspecting it in detail, but I couldn't find any calls to it, or methods with that name in the underlying MessagePassing class from pyg.

2. The second relates to the L2 regularization parameter on the distances between the graphs. It seems that the computation of the distance is commented out in the [file](https://github.com/WenjieDu/PyPOTS/blob/main/pypots/classification/raindrop/modules/core.py) (lines 221, 222). Is the regulariser used and called elsewhere? Or was it removed in later iterations of the model?

Best, and thank you very much once again!
Lucas

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hi Lucas, thanks for raising this discussion. 

We make code logic the same as the official implementation https://github.com/mims-harvard/Raindrop. Yes, some objects and functions don't get used in the model processing procedure. They are kept here in case the official repo gets updated.

**Comment by lucasmiranda42** [comment]
Hey, thank you for your answer! I'll try to reach out to the original authors, then :)

Best,
Lucas

**Comment by WenjieDu** [comment]
Lucas has opened an issue in the Raindrop official repo https://github.com/mims-harvard/Raindrop/issues/11.

I'm closing this issue for now. If there is any further related problem that should be fixed in PyPOTS, reopening will be welcome.
