### ISSUE TITLE
PyPOTS_tutorials.ipynb not working due to Old Edition

### ISSUE THREAD

**Issue by Six-Persimmon** [WenjieDu/PyPOTS#305]
### 1.Problem Discription

1. In the online Colab tutorial file enclosed in the "Quick-start Examples" section of the PyPOTS document, the codes start with an out-of-date  line `! pip install pypots==0.1.1`that causes a tsdb problem in line `physionet2012_dataset = gene_physionet2012(artificially_missing_rate=0.1)`. 
The problem can be solved by instead using `! pip install pypots==0.3.1`. 

2. In all the tutorial files, the dataset obtained by:

`physionet2012_dataset = gene_physionet2012(artificially_missing_rate=0.1)`

does not contain the key "val_X_intact". Therefore the following cell line:

```
dataset_for_validating = {
    "X": physionet2012_dataset['val_X'],
    "X_intact": physionet2012_dataset['val_X_intact'],
    "indicating_mask": physionet2012_dataset['val_X_indicating_mask'],
}
```

Will report error: `KeyError: 'val_X_intact'`

### 3. Reproduction

1.Click "You can also find a simple and quick-start tutorial notebook on Google Colab with [this link](https://colab.research.google.com/drive/1HEFjylEy05-r47jRy0H9jiS_WhD0UWmQ?usp=sharing)." in the quick start document.
2. Run the code, it will report the errors.

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Thanks, Shijian @Six-Persimmon. I'll update the tutorials on Colab and in the BrewPOTS repo https://github.com/WenjieDu/BrewPOTS. Any interest in joining our community and collaborating?

**Comment by Six-Persimmon** [comment]
Thank you Wenjie! YES! I am reaching out to the contributor Yinghao (we have been friends since middle school😆) to see if PyPOTS can solve a specific group of Economic problems I am working on, and am very willing to join the community. Thank you for this awesome project!
