### ISSUE TITLE
how to download pygrinder

### ISSUE THREAD

**Issue by jichangduan** [WenjieDu/PyPOTS#319]
### Issue description

pip pygrinder
ERROR: unknown command "pygrinder"

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hi, read the guideline here https://github.com/WenjieDu/PyGrinder?tab=readme-ov-file#-usage-examples.

If pygrinder is useful to you, please star🌟 its repo to help more people notice this tool https://github.com/WenjieDu/PyGrinder. Thank you.
