### ISSUE TITLE
Question for the no-missing dataset inputs in SAITS

### ISSUE THREAD

**Issue by miten073** [WenjieDu/PyPOTS#360]
### Issue description

hi , after reading the quick strat of pypots , i would like to ask u some questions.
1.How can I use pypots to verify the performance of the SAITS model if I'm entering a dataset where the raw data doesn't contain missing values?For example, for datasets that do not themselves contain missing values, I used mcar( ) to manually randomly miss 10% of the original data, and then entered fit( ) for training, will fit( ) treat my missing 10% of my implementation as original missing?
2. On the basis of 1, if fit( ) treats my artificial missing 10% of my data as raw missing when training, will he then randomly miss a part of the value when training to complete an MIT task?
3.After reading quick start, I was confused about how to use pypots to train, validate, and test the data without the missing dataset in SAITS. If you can, would you please give a code example that shows how to train, validate, and test for data that does not itself contain missing data ?
Looking forward to your reply

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
It seems that you're not familiar with the imputation literature. To validate the model's imputation performance on a dataset without missing data, you should mask out a part of the observed values in the original dataset and hold out them as the test set.

Seriously, I suggest you to read some time-series imputation papers, e.g. BRITS and SAITS https://arxiv.org/pdf/2202.08516, and read them well. PyPOTS is built to help people work with POTS data easily, but that doesn't mean you don't have to learn things about POTS.
