### ISSUE TITLE
Add an argument `verbose` for all models

### ISSUE THREAD

**Issue by WenjieDu** [WenjieDu/PyPOTS#394]
### 1. Feature description

Add a boolean argument `verbose` for all models to determine whether to print detailed training logs.

### 2. Motivation

To avoid printing too much information during training that may be annoying.

### 3. Your contribution

Will make a PR to accomplish this.

**Comment by Albert2020-05** [comment]
I would like to give this task a try and see if I can handle it.

**Comment by WenjieDu** [comment]
Hi Haoyang @Albert2020-05, no problem, enjoy your coding ;-) 

I'll help review your code once your PR is submitted. Note that if you want to modify, please only modify the necessary part of the code related to this issue and leave the unrelated part intact.
