### ISSUE TITLE
Could I use the imputation methods to upsample my low-frequency data?

### ISSUE THREAD

**Issue by mike-egg123** [WenjieDu/PyPOTS#419]
### Issue description

Hello, Mr. Du! I am a graduate student from the School of Software at Beihang University, majoring in time series analysis. I have been researching time series imputation recently and happened to see your related research, including papers and codes, which has greatly inspired me. Now I have a small question to ask you, can the imputation method be applied to the task of upsampling low-frequency data? My initial idea is to use the resample method of data analysis libraries such as Pandas to resample low-frequency data at a higher frequency. At this time, there will be many missing data. For these missing data, use the model in your PYPOTS library for imputation. Do you think this approach is reasonable?

**Comment by WenjieDu** [comment]
Hi @mike-egg123, worth a shot, but the final results depend on your data's attributes, e.g. the original sampling freq of raw data. You can reach out to me on WeChat.

**Comment by mike-egg123** [comment]
好的，我已经向您的微信发送了好友申请，麻烦您通过一下
