### ISSUE TITLE
multivariate time series forecasting

### ISSUE THREAD

**Issue by LongWuAha** [WenjieDu/PyPOTS#456]
### Issue description

Hello, may I ask how PyPOTS can predict multivariate time-series data? Can you provide an example? Thank you!

**Comment by WenjieDu** [comment]
@LongWuAha Check out the tutorials here https://github.com/WenjieDu/BrewPOTS.

And we will make more neural networks in PyPOTS applicable to the forecasting task in the near future. Stay tuned please!
