### ISSUE TITLE
Request to add linear interpolation imputation method as a new naive model

### ISSUE THREAD

**Issue by colesussmeier** [WenjieDu/PyPOTS#457]
### 1. Model description

Linear interpolation (Lerp) imputation method:
- Lerp will linearly interpolate missing values between the nearest non-missing values.
- If there are missing values at the beginning or end of the series, they will be back-filled or forward-filled with the nearest non-missing value, respectively.
- If an entire series is empty, all 'nan' values will be filled with zeros.

I think linear interpolation is a great naive baseline to compare more complicated models to, and would love to see it become part of PyPOTS! I have the code implemented already, so I can make a PR to dev with your consent. 

### 2. Check open-source status

- [X] The model implementation is publicly available

### 3. Provide useful information for the implementation

Implementation is relatively straight-forward and uses [numpy.interp](numpy.interp) under the hood. I don't have an official paper on it for this use-case but it has been widely used in many domains for many years. Please let me know if you have any questions and if I can submit a PR! Email: colesussmeier@gmail.com :)

**Comment by WenjieDu** [comment]
Thanks for proposing this idea, @colesussmeier! We previously used pandas to help generate linear interpolation results, but I think it would be cool to add one implementation into PyPOTS ;-)  Could you please make a PR to submit yours? I'll help review your code.
