### ISSUE TITLE
Multivariate regression task

### ISSUE THREAD

**Issue by IKetchup** [WenjieDu/PyPOTS#458]
### Issue description

Hello, thank you for your amazing work. I would like to use PyPOTS in my research with timeseries.

I woud like to train a model to predict 3D timeseries from other  differents 3D timeseries. My goal is to use timeseries of shape (batch_size, len_size, input_features) to predict differents timeseries of shape (batch_size, len_size, output_features) with input_features different from output_features (no commun features). Is it possible to do so as this type of problem is not exaclty seen as forcasting and if possible how should I start ?

Thnaks in advance

**Comment by WenjieDu** [comment]
@IKetchup Thanks for your attention to our work. So far there is no model in PyPOTS supporting such a task. But we will add one soon. Please stay tuned, and you can follow me to get notified of updates on all PyPOTS toolkits in the future.
