### ISSUE TITLE
Model saving bug

### ISSUE THREAD

**Issue by WenjieDu** [WenjieDu/PyPOTS#464]
### 1. System Info

PyPOTS v0.6

### 2. Information

- [X] The official example scripts
- [ ] My own created scripts

### 3. Reproduction

When `model_saving_strategy` is set as better, PyPOTS doesn't save models when loss gets decreased.

### 4. Expected behavior

Models should be properly saved

**Comment by vemuribv** [comment]
Hi @WenjieDu! I think this may have had an unintended effect--now (in v0.7 and later) even when model_saving_strategy is set as "best", PyPOTS saves the model every time the loss is decreased. In v0.6, setting to "best" had the intended behavior (saving only the best model at the very end after training is finished).

**Comment by WenjieDu** [comment]
Bug confirmed. Thank you, @vemuribv! I should have taken `model_saving_strategy` into consideration within `confirm_saving` when saving, but I forgot to do so when global replacing.

I'm reopening this issue and going to submit a PR to fix this. Could you please help review it?

**Comment by WenjieDu** [comment]
@vemuribv PR submitted. You are also very welcome to propose a better way to optimize the current saving strategy ;-)
