### ISSUE TITLE
long time series

### ISSUE THREAD

**Issue by mrezasaatchi** [WenjieDu/PyPOTS#473]
### Issue description

Hello. Each of my signals has 15000 timesteps. When I try to impute the signal with the SAITS imputation model, I run out of graphics memory. What is the solution for this problem?

**Comment by WenjieDu** [comment]
Try to slice your long time series with `pypots.data.utils.sliding_window`.

**Comment by mrezasaatchi** [comment]
I have attempted to address this issue independently, but regrettably, the consideration of dependencies between signals outside the windows was not achieved. I have set the length of each window to 500; however, there are instances where our signals contain a window with NaN values that exceed this length. In your “sliding_window” function, if you have any suggestions on how to incorporate learning the dependencies between points beyond each window, I would greatly appreciate your input.

**Comment by WenjieDu** [comment]
If your application scenario requests such long time series input, I'd suggest you use RNN models, like BRITS. But it will take quite a long time for processing I think. It's a time-space trade-off.

If our work is helpful to you, please star our work to make more people notice it ;-)
