### ISSUE TITLE
Loading your own dataset to pypots.

### ISSUE THREAD

**Issue by UmerrAhsan** [WenjieDu/PyPOTS#485]
### Issue description

How to load your own dataset to pypots and run the imputation algorithms on them? Can anyone please help or give me the direction.

**Comment by WenjieDu** [comment]
Check out the data processing scripts in [Awesome_Imputation](https://github.com/WenjieDu/Awesome_Imputation/tree/main/benchmark_code/data). Read the source code of TSDB and BenchPOTS.
