### ISSUE TITLE
ask some question about modle

### ISSUE THREAD

**Issue by xxzhao1997** [WenjieDu/PyPOTS#486]
### Issue description

Hello,

I've encountered some issues while using your project to impute my collected electricity data. Specifically, there are many spikes in the results for data with minimal fluctuations. Additionally, I tried using your provided electricity_load_diagrams dataset and observed the same phenomenon.

Have you experienced similar issues when using this project? If so, could you recommend any models or data processing methods to improve this situation? Thank you!
![Uploading Snipaste_2024-08-06_15-24-42.png…]()

**Comment by WenjieDu** [comment]
Your pic failed to be uploaded. Please try again.

**Comment by xxzhao1997** [comment]
![Snipaste_2024-08-06_15-24-42](https://github.com/user-attachments/assets/147f8f21-d8dd-46ba-b0ba-1e2a76cae046)

**Comment by xxzhao1997** [comment]
![Uploading Snipaste_2024-08-06_15-24-42.png…]()

**Comment by WenjieDu** [comment]
This issue could be the result of the following factors:

1. the imputation results of this feature get affected by other ones which fluctuate more;
2. the model is underfitting or its capacity is not able to handle the problem, and its hyperparameters should be tuned and adjusted;
