### ISSUE TITLE
Time-Series.AI logo is printed on the console output at each import. How can I make it smaller or disable it?

### ISSUE THREAD

**Issue by giacomoguiduzzi** [WenjieDu/PyPOTS#529]
### Issue description

Greetings,

As the title indicates, I updated PyPOTS from version 0.6 to 0.8.1. Importing the library into a module now causes a huge logo (screenshot attached) to be drawn on the console output. I have no problem with it, except that since I am using multiprocessing this logo is being spammed on the console output each time a new worker imports the module. Is there some global setting I can use to make it smaller or maybe print it only once at the beginning through an if block, or something like that?
Thank you in advance, I'm looking forward to your kind response.

Best Regards,
Giacomo Guiduzzi

![pypots_timeseries_ai_logo](https://github.com/user-attachments/assets/8bb4e0b8-b3ff-4a47-8c1a-ad0d659cde03)

**Comment by petteriTeikari** [comment]
Yes, some `logo_verbose = False` flag could be nice as requested by @giacomoguiduzzi :)
