### ISSUE TITLE
Add CSAI

### ISSUE THREAD

**Issue by LinglongQian** [WenjieDu/PyPOTS#536]
### 1. Model description

CSAI should be included in PyPOTS as an imputation model.

```bibtex
@article{qian2023knowledge,
  title={Knowledge Enhanced Conditional Imputation for Healthcare Time-series},
  author={Qian, Linglong and Ibrahim, Zina and Ellis, Hugh Logan and Zhang, Ao and Zhang, Yuezhou and Wang, Tao and Dobson, Richard},
  journal={arXiv preprint arXiv:2312.16713},
  year={2023}
}
```

### 2. Check open-source status

- [X] The model implementation is publicly available

### 3. Provide useful information for the implementation

https://github.com/LINGLONGQIAN/CSAI

**Comment by WenjieDu** [comment]
Hi @LinglongQian @joseph-arulraj, I found that CSAI cannot accept dataset files for lazy loading because normalization mean and std need to be calculated ahead, as mentioned in issue #544. I fixed this in PR #545. Have a review please.
