### ISSUE TITLE
Beta parameter is ignored in GPVAE when using the IWAE setting

### ISSUE THREAD

**Issue by AlexandreAbraham** [WenjieDu/PyPOTS#540]
### Issue description

In the backbone of GPVAE, a different path is taken depending on whether IWAE is used or not.

In the case K=1, the elbo is [updated like this](https://github.com/WenjieDu/PyPOTS/blob/bf045b4889637586b4fbf084dc7ee0470768f51f/pypots/nn/modules/gpvae/backbone.py#L183):
```python
elbo = -nll - self.beta * kl
```
In the case K>1, the elbo is [updated like that](https://github.com/WenjieDu/PyPOTS/blob/bf045b4889637586b4fbf084dc7ee0470768f51f/pypots/nn/modules/gpvae/backbone.py#L173):
```python
elbo = -nll - kl
```

I understand that those usages are different, but it feels wrong to me to silently ignore a parameter. Also, I do not see why beta could not be applied in the IWAE case. I therefore suggest one of:
* [ ] Raise a warning if K is set >1 and Beta is specified by the user to avoid misunderstanding
* [ ] Change the IWAE loss to be computer as the beta-VAE one.

Let me know so I can propose a PR.

Thanks for the great software!

**Comment by AlexandreAbraham** [comment]
Still not resolved AFAIK

**Comment by AugustJW** [comment]
Hi Alexander,

Apologies for the delayed response, and thank you very much for pointing this out!

At this stage, we would like to stay consistent with the official [GP-VAE implementation](https://github.com/ratschlab/GP-VAE/blob/6e06c93d37d07ede2eb1f578b577c80a59846e2c/lib/models.py#L290). Additionally, there doesn't appear to be any established foundation or implementation for combining beta with IWAE. Given this, we believe the most appropriate solution would be to raise a warning when K > 1 and beta is specified, as you suggested.

If you're interested in proceeding with a PR to implement this warning, we'd be happy to review it. Thanks again for your valuable contribution to improving the software!

**Comment by AlexandreAbraham** [comment]
No problem, it's a very minor issue, I understand that it's not a priority ;).
I'll push a PR soon.
