### ISSUE TITLE
Please release package source on PyPI

### ISSUE THREAD

**Issue by sugatoray** [WenjieDu/PyPOTS#9]
Currently only a `.whl` file is available on PyPI. Please release both the `.whl` file and the source (`*.tar.gz`) file on PyPI.

![image](https://user-images.githubusercontent.com/10201242/181269354-c639a8bd-4335-4f5f-95ad-833884252fec.png)

**Comment by sugatoray** [comment]
cc: @WenjieDu

**Comment by WenjieDu** [comment]
Hi there,<br><br>Thank you so much for your attention to PyPOTS! If you find PyPOTS helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution.<br><br>I have received your message and will respond ASAP. Thank you for your patience! 😃<br><br>Best,<br>Wenjie

**Comment by WenjieDu** [comment]
Thank you very much for your suggestion, Sugato! I'll release the source code as the tar file together with the wheel in the next version.

**Comment by WenjieDu** [comment]
In PR #14, I added a workflow to automatically publish a package (with both a wheel and the source code) to PyPI when creating a new release on GitHub. Not tested yet. Will close this issue after passing the test in the next release.

**Comment by WenjieDu** [comment]
The automation workflow works as expected. Check the result here [https://pypi.org/project/pypots/#files](https://pypi.org/project/pypots/#files).
